#Importing libraries

In [ ]:
# import required libraries
import pandas as pd
import numpy as np

#Loading dataset

In [ ]:
# Reading the dataset
df = pd.read_csv('/content/50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

#Data pre-processing

In [ ]:
df.shape

(108, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [ ]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [ ]:
df['State'] = le.fit_transform(df.State)

In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

#Data spliting and training

In [ ]:
X =df.iloc[:,:-1].values

In [ ]:
y= df.iloc[:,4:5].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
x_train.shape, x_test.shape

((75, 4), (33, 4))

#ANN

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# creating ANN skeleton

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))
regressor.add(Dense(12,activation='relu'))
regressor.add(Dense(8,activation='relu'))
regressor.add(Dense(9,activation='relu'))
regressor.add(Dense(1,activation='linear'))


In [ ]:
# Compiling ANN model

regressor.compile(optimizer='adam',loss ='mse',metrics=['mse'] )

In [ ]:
# training the model
regressor.fit(x_train,y_train,batch_size=10,epochs =300)

Epoch 1/300
8/8 [==============================] - 2s 4ms/step - loss: 12323623936.0000 - mse: 12323625984.0000
Epoch 2/300
8/8 [==============================] - 0s 3ms/step - loss: 11309795328.0000 - mse: 11309795328.0000
Epoch 3/300
8/8 [==============================] - 0s 3ms/step - loss: 10265518080.0000 - mse: 10265518080.0000
Epoch 4/300
8/8 [==============================] - 0s 3ms/step - loss: 9059274752.0000 - mse: 9059274752.0000
Epoch 5/300
8/8 [==============================] - 0s 3ms/step - loss: 7619367424.0000 - mse: 7619366400.0000
Epoch 6/300
8/8 [==============================] - 0s 4ms/step - loss: 6229254656.0000 - mse: 6229254656.0000
Epoch 7/300
8/8 [==============================] - 0s 3ms/step - loss: 4845008384.0000 - mse: 4845008384.0000
Epoch 8/300
8/8 [==============================] - 0s 3ms/step - loss: 3598469888.0000 - mse: 3598469888.0000
Epoch 9/300
8/8 [==============================] - 0s 3ms/step - loss: 2556743424.0000 - mse: 2556743424.0000
Epoc

In [ ]:
# testing the model

y_pred = regressor.predict(x_test)

2/2 [==============================] - 0s 6ms/step


In [ ]:
y_pred

array([[ 42480.96 ],
       [125685.62 ],
       [ 80467.15 ],
       [174656.36 ],
       [ 96692.516],
       [120942.41 ],
       [127043.35 ],
       [165222.77 ],
       [117338.836],
       [ 45489.914],
       [103134.11 ],
       [119146.33 ],
       [ 42480.96 ],
       [131633.   ],
       [ 65611.266],
       [129702.07 ],
       [129702.07 ],
       [102903.945],
       [ 69000.57 ],
       [141143.3  ],
       [155067.75 ],
       [158639.92 ],
       [109371.836],
       [159814.27 ],
       [ 91568.15 ],
       [171853.92 ],
       [124724.97 ],
       [ 17732.977],
       [ 87063.375],
       [147908.33 ],
       [ 69973.305],
       [200547.98 ],
       [200539.69 ]], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
# evaluating the model with r2 score

r2_score(y_test,y_pred)

0.8893362700324977

In [ ]:
y_pred.flatten()

array([ 42480.96 , 125685.62 ,  80467.15 , 174656.36 ,  96692.516,
       120942.41 , 127043.35 , 165222.77 , 117338.836,  45489.914,
       103134.11 , 119146.33 ,  42480.96 , 131633.   ,  65611.266,
       129702.07 , 129702.07 , 102903.945,  69000.57 , 141143.3  ,
       155067.75 , 158639.92 , 109371.836, 159814.27 ,  91568.15 ,
       171853.92 , 124724.97 ,  17732.977,  87063.375, 147908.33 ,
        69973.305, 200547.98 , 200539.69 ], dtype=float32)

In [ ]:
# Comparing the actual and predicted y values

pd.DataFrame({'Actual y_value':y_test.flatten(),'Predicted y_value':y_pred.flatten()}).head(10)

Actual y_value  Predicted y_value
0        64926.08       42480.960938
1       146121.95      125685.617188
2        90708.19       80467.148438
3       191050.39      174656.359375
4       108552.04       96692.515625
5       144259.40      120942.406250
6       124266.90      127043.351562
7       155752.60      165222.765625
8       126992.93      117338.835938
9        42559.73       45489.914062

In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [ ]:
# testing with random values

regressor.predict([[142107.34,91391.77,366168.42,2]])

1/1 [==============================] - 0s 41ms/step


array([[159815.72]], dtype=float32)

In [ ]:
regressor.predict([[144107.12,118671.85,12345.42,0]])

1/1 [==============================] - 0s 51ms/step


array([[119225.58]], dtype=float32)